:fn-stand-hauptrechner: footnote:[Hauptrechner auf Arch LInux, Stand 11/2025]

= Einrichtung auf bestehenden Arch-Linux-Systemen

== Klassifizierung
Betriebssystem:: Arch
Zeitpunkt:: Neues/Bestehendes System
Berechtigungen:: Root

== Beschreibung

Primärer Zweck des Repos ist die Verwendung auf neuen und bestehenden Arch-Installationen,
wie meinem derzeitigen Hauptrechner{fn-stand-hauptrechner}.

== Einrichtung
Zur Verwendung der Konfigurationen auf einem bestehenden Arch-Linux-Gerät sind ein paar einfache
Schritte durchzuführen:

=== Vorbereitung

[source,shell]
----
sudo pacman -Syu
yay -S decman
----

Der deklarative Paketmanager `decman` muss aus dem AUR installiert werden.
Dies kann über `yay` oder manuell erfolgen.
Eine detaillierte Anleitung mit Beispiel ist auf https://github.com/kiviktnm/decman/blob/71a7e867ad9c128ac235f9e8a6ae04ea4b6205e0/example/README.md[Github]
zu finden.

=== Auswahl eines Hosts
Für das System muss eine entsprechende `hostname.py` Datei im `hosts` Verzeichnis enthalten sein.
Diese beinhaltet alle notwendigen Verweise auf die benötigten Module.

Der Zugriff kann nun über eine kurze Einstiegs-Konfigurationsdatei erfolgen.
Im Fall meines Hauptrechners sieht das so aus:

[source,python]
.~/.config/decman/local_config.py
----
import decman
from hosts.techtornado_arch import TechtornadoArch

decman.modules += [TechtornadoArch()]
----

Über ein Bash-Alias führe ich nun folgende Schritte automatisiert aus:

. Repository nach `~/.config/my-configs` klonen
. Lokale Konfiguration in `~/.config/my-configs` kopieren
. Ausführung von Decman mit Adminrechten

[source,bash]
----
alias update-desktop='[ -d "$HOME/.config/my-configs" ] && (cd "$HOME/.config/my-configs" && git pull) || git clone https://github.com/Hirschfuchs/my-configs.git "$HOME/.config/my-configs" && cp "$HOME/.config/decman/local_config.py" "$HOME/.config/my-configs/config.py" && sudo decman --source "$HOME/.config/my-configs/config.py"'
----

Auf diese Weise wird stets der aktuellste Main-Stand installiert.
