= Moduldokumentation
Beschreibung der im Repo enthaltenen Module

Diese Dokumentation beschreibt die konfigurierten Decman-Module.
Sie soll den Entwurf der Modulstruktur festhalten und die Entscheidung
über zu verwendende Module für einen neuen Host unterstützen.

== Allgemeine Strukturierung

Die Module teilen sich in mehrere Schichten auf.

[plantuml]
----
@startuml
component mod [
Module (Hauptebene)
]
component sub [
Submodule
]

mod -down-> sub
@enduml
----

Auf der oberen Ebene sind abstraktere Gruppen, wie "Arbeit" oder "Gaming" beschrieben,
während auf der Submodul-Ebene die konkreten Abhängigkeiten gelistet sind.

== Dokumentation der einzelnen Module

Jedes installierte Paket soll einen zugehörigen Kommentar erhalten, welcher dessen Zweck beschreibt.
Eine Aufschlüsselung aller Pakete in der Dokumentation, wie ursprünglich geplant, wird nicht erfolgen,
da diese schnell von der tatsächlichen Deklaration abweicht.
Die automatische Erzeugung der Dokumentation kann in der Zukunft in Erwägung gezogen werden.
